global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  
  - job_name: 'variant-a-jmx'
    static_configs:
      - targets: ['variant-a:9404']
    - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'variant-a'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'variant-c'
  metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'variant-d'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
